# Generated by Django 4.1.7 on 2023-04-05 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('medical_condition', models.TextField(blank=True)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('id_type', models.CharField(max_length=50)),
                ('id_card_no', models.CharField(max_length=20, unique=True)),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='id_images/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lga', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=300)),
                ('accepting_applications', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MosqueAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.mosque')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('additional_info', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itikaf.mosqueadmin')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.CharField(max_length=30, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itikaf.mosqueadmin')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.CharField(max_length=30, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itikaf.mosqueadmin')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itikaf.mosqueadmin')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itikaf.mosqueadmin'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.mosque'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('name', 'age', 'address', 'next_of_kin_phone')},
        ),
    ]
