# Generated by Django 4.1.7 on 2023-04-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set(),
        ),
    ]
