# Generated by Django 4.1.7 on 2023-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
