# Generated by Django 4.1.7 on 2023-03-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0002_alter_applicant_id_image_alter_applicant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/'),
        ),
    ]
