# Generated by Django 4.1.7 on 2023-03-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0005_remove_processing_approved_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Processing',
            new_name='Approval',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='approval',
            name='approved',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(max_length=30)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itikaf.mosqueadmin')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.CharField(max_length=30)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itikaf.mosqueadmin')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.CharField(max_length=30)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itikaf.mosqueadmin')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant')),
            ],
        ),
    ]
