# Generated by Django 4.1.7 on 2023-03-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0006_rename_processing_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_in',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='check_out',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='additional_info',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
