# Generated by Django 4.1.7 on 2023-03-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0007_alter_approval_approved_alter_checkin_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itikaf.applicant'),
        ),
    ]
