# Generated by Django 4.1.7 on 2023-03-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0009_approval_date_added_checkin_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved',
            field=models.CharField(default='Disapproved', max_length=30),
        ),
    ]
