# Generated by Django 4.1.7 on 2023-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0010_alter_approval_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
