# Generated by Django 4.1.7 on 2023-04-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itikaf', '0014_approval_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='action',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='additional_info',
            field=models.CharField(max_length=500),
        ),
    ]
